class matthewdata {
  final int id;
  final String title;

  const matthewdata({
    required this.id,
    required this.title,
  });
}

const matthew_data = [
  matthewdata(id: 1, title: 'chapter1'),
  matthewdata(id: 2, title: 'chapter2'),
  matthewdata(id: 3, title: 'chapter3'),
  matthewdata(id: 4, title: 'chapter4'),
  matthewdata(id: 5, title: 'chapter5'),
  matthewdata(id: 6, title: 'chapter6'),
  matthewdata(id: 6, title: 'chapter7'),
  matthewdata(id: 8, title: 'chapter8'),
  matthewdata(id: 9, title: 'chapter9'),
  matthewdata(id: 10, title: 'chapter10'),
  matthewdata(id: 11, title: 'chapter11'),
  matthewdata(id: 12, title: 'chapter12'),
  matthewdata(id: 13, title: 'chapter13'),
  matthewdata(id: 14, title: 'chapter14'),
  matthewdata(id: 15, title: 'chapter15'),
  matthewdata(id: 16, title: 'chapter16'),
  matthewdata(id: 17, title: 'chapter17'),
  matthewdata(id: 18, title: 'chapter18'),
  matthewdata(id: 19, title: 'chapter19'),
  matthewdata(id: 20, title: 'chapter20'),
  matthewdata(id: 21, title: 'chapter21'),
  matthewdata(id: 22, title: 'chapter22'),
  matthewdata(id: 23, title: 'chapter23'),
  matthewdata(id: 24, title: 'chapter24'),
  matthewdata(id: 25, title: 'chapter25'),
  matthewdata(id: 26, title: 'chapter26'),
  matthewdata(id: 27, title: 'chapter27'),
  matthewdata(id: 28, title: 'chapter28'),
];

final List<String> chapternumber = [
  'Chapter 1',
  'Chapter 2',
  'Chapter 3',
  'Chapter 4',
  'Chapter 5',
  'Chapter 6',
  'Chapter 7',
  'Chapter 8',
  'Chapter 9',
  'Chapter 10',
  'Chapter 11',
  'Chapter 12',
  'Chapter 13',
  'Chapter 14',
  'Chapter 15',
  'Chapter 16',
  'Chapter 17',
  'Chapter 18',
  'Chapter 19',
  'Chapter 20',
  'Chapter 21',
  'Chapter 22',
  'Chapter 23',
  'Chapter 24',
  'Chapter 25',
  'Chapter 26',
  'Chapter 27',
  'Chapter 28',
  'Chapter 29',
  'Chapter 30',
  'Chapter 31',
  'Chapter 32',
  'Chapter 33',
  'Chapter 34',
  'Chapter 35',
  'Chapter 36',
  'Chapter 37',
  'Chapter 38',
  'Chapter 39',
  'Chapter 40',
  'Chapter 41',
  'Chapter 42',
  'Chapter 43',
  'Chapter 44',
  'Chapter 45',
  'Chapter 46',
  'Chapter 47',
  'Chapter 48',
  'Chapter 49',
  'Chapter 50',
];
