class GenesisChapters {
  final int id;
  final String title;
  final String biblecategory;
  GenesisChapters({
    required this.id,
    required this.title,
    required this.biblecategory,
  });
}

//list of Genesischapters
List<GenesisChapters> genesischapter = [
  GenesisChapters(id: 1, biblecategory: '創世記', title: 'chapter 1'),
  GenesisChapters(id: 2, biblecategory: '創世記', title: 'chapter 2'),
  GenesisChapters(id: 3, biblecategory: '創世記', title: 'chapter 3'),
  GenesisChapters(id: 4, biblecategory: '創世記', title: 'chapter 4'),
  GenesisChapters(id: 5, biblecategory: '創世記', title: 'chapter 5'),
  GenesisChapters(id: 6, biblecategory: '創世記', title: 'chapter 6'),
  GenesisChapters(id: 7, biblecategory: '創世記', title: 'chapter 7'),
  GenesisChapters(id: 8, biblecategory: '創世記', title: 'chapter 8'),
  GenesisChapters(id: 9, biblecategory: '創世記', title: 'chapter 9'),
  GenesisChapters(id: 10, biblecategory: '創世記', title: 'chapter 10'),
  GenesisChapters(id: 11, biblecategory: '創世記', title: 'chapter 11'),
  GenesisChapters(id: 12, biblecategory: '創世記', title: 'chapter 12'),
  GenesisChapters(id: 13, biblecategory: '創世記', title: 'chapter 13'),
  GenesisChapters(id: 14, biblecategory: '創世記', title: 'chapter 14'),
  GenesisChapters(id: 15, biblecategory: '創世記', title: 'chapter 15'),
  GenesisChapters(id: 16, biblecategory: '創世記', title: 'chapter 16'),
  GenesisChapters(id: 17, biblecategory: '創世記', title: 'chapter 17'),
  GenesisChapters(id: 18, biblecategory: '創世記', title: 'chapter 18'),
  GenesisChapters(id: 19, biblecategory: '創世記', title: 'chapter 19'),
  GenesisChapters(id: 20, biblecategory: '創世記', title: 'chapter 20'),
  GenesisChapters(id: 21, biblecategory: '創世記', title: 'chapter 21'),
  GenesisChapters(id: 22, biblecategory: '創世記', title: 'chapter 22'),
  GenesisChapters(id: 23, biblecategory: '創世記', title: 'chapter 23'),
  GenesisChapters(id: 24, biblecategory: '創世記', title: 'chapter 24'),
  GenesisChapters(id: 25, biblecategory: '創世記', title: 'chapter 25'),
  GenesisChapters(id: 26, biblecategory: '創世記', title: 'chapter 26'),
  GenesisChapters(id: 27, biblecategory: '創世記', title: 'chapter 27'),
  GenesisChapters(id: 28, biblecategory: '創世記', title: 'chapter 28'),
  GenesisChapters(id: 29, biblecategory: '創世記', title: 'chapter 29'),
  GenesisChapters(id: 30, biblecategory: '創世記', title: 'chapter 30'),
  GenesisChapters(id: 31, biblecategory: '創世記', title: 'chapter 31'),
  GenesisChapters(id: 32, biblecategory: '創世記', title: 'chapter 32'),
  GenesisChapters(id: 33, biblecategory: '創世記', title: 'chapter 33'),
  GenesisChapters(id: 34, biblecategory: '創世記', title: 'chapter 34'),
  GenesisChapters(id: 35, biblecategory: '創世記', title: 'chapter 35'),
  GenesisChapters(id: 36, biblecategory: '創世記', title: 'chapter 36'),
  GenesisChapters(id: 37, biblecategory: '創世記', title: 'chapter 37'),
  GenesisChapters(id: 38, biblecategory: '創世記', title: 'chapter 38'),
  GenesisChapters(id: 39, biblecategory: '創世記', title: 'chapter 39'),
  GenesisChapters(id: 40, biblecategory: '創世記', title: 'chapter 40'),
  GenesisChapters(id: 41, biblecategory: '創世記', title: 'chapter 41'),
  GenesisChapters(id: 42, biblecategory: '創世記', title: 'chapter 42'),
  GenesisChapters(id: 43, biblecategory: '創世記', title: 'chapter 43'),
  GenesisChapters(id: 44, biblecategory: '創世記', title: 'chapter 44'),
  GenesisChapters(id: 45, biblecategory: '創世記', title: 'chapter 45'),
  GenesisChapters(id: 46, biblecategory: '創世記', title: 'chapter 46'),
  GenesisChapters(id: 47, biblecategory: '創世記', title: 'chapter 47'),
  GenesisChapters(id: 48, biblecategory: '創世記', title: 'chapter 48'),
  GenesisChapters(id: 49, biblecategory: '創世記', title: 'chapter 49'),
  GenesisChapters(id: 50, biblecategory: '創世記', title: 'chapter 50'),
];
