import 'package:flutter/material.dart';

class Psalmmenu extends ChangeNotifier {
  final String japaneseTitle;
  final String englishTitle;
  final String copticTitle;
  final String arabicTitle;
  final int index;

  Psalmmenu({
    required this.copticTitle,
    required this.japaneseTitle,
    required this.englishTitle,
    required this.arabicTitle,
    required this.index,
  });
  List<Psalmmenu> get psalmmenu1 => menu;
  static List<Psalmmenu> menu = [
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 1( )',
      englishTitle: 'psalm 1',
      arabicTitle: 'مزامير 1',
      index: 0,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 2( )',
      englishTitle: 'psalm 2',
      arabicTitle: 'مزامير 2',
      index: 1,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 3( )',
      englishTitle: 'psalm 3',
      arabicTitle: 'مزامير 3',
      index: 2,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 4( )',
      englishTitle: 'psalm 4',
      arabicTitle: 'مزامير 4',
      index: 3,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 5( )',
      englishTitle: 'psalm 5',
      arabicTitle: 'مزامير 5',
      index: 4,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 6( )',
      englishTitle: 'psalm 6',
      arabicTitle: 'مزامير 6',
      index: 5,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 7( )',
      englishTitle: 'psalm 7',
      arabicTitle: 'مزامير 7',
      index: 6,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 8( )',
      englishTitle: 'psalm 8',
      arabicTitle: 'مزامير 8',
      index: 7,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 9( )',
      englishTitle: 'psalm 9',
      arabicTitle: 'مزامير 9',
      index: 8,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 10( )',
      englishTitle: 'psalm 10',
      arabicTitle: 'مزامير 10',
      index: 9,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 11( )',
      englishTitle: 'psalm 11',
      arabicTitle: 'مزامير 11',
      index: 10,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 12( )',
      englishTitle: 'psalm 12',
      arabicTitle: 'مزامير 12',
      index: 11,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 14( )',
      englishTitle: 'psalm 14',
      arabicTitle: 'مزامير 14',
      index: 12,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 15( )',
      englishTitle: 'psalm 15',
      arabicTitle: 'مزامير 15',
      index: 13,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 18( )',
      englishTitle: 'psalm 18',
      arabicTitle: 'مزامير 18',
      index: 14,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 19( )',
      englishTitle: 'psalm 19',
      arabicTitle: 'مزامير 19',
      index: 15,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 22( )',
      englishTitle: 'psalm 22',
      arabicTitle: 'مزامير 22',
      index: 16,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 23( )',
      englishTitle: 'psalm 23',
      arabicTitle: 'مزامير 23',
      index: 17,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 24( )',
      englishTitle: 'psalm 24',
      arabicTitle: 'مزامير 24',
      index: 18,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 25( )',
      englishTitle: 'psalm 25',
      arabicTitle: 'مزامير 25',
      index: 19,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 26( )',
      englishTitle: 'psalm 26',
      arabicTitle: 'مزامير 26',
      index: 20,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 28( )',
      englishTitle: 'psalm 28',
      arabicTitle: 'مزامير 28',
      index: 21,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 29( )',
      englishTitle: 'psalm 29',
      arabicTitle: 'مزامير 29',
      index: 22,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 33( )',
      englishTitle: 'psalm 33',
      arabicTitle: 'مزامير 33',
      index: 23,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 40( )',
      englishTitle: 'psalm 40',
      arabicTitle: 'مزامير 40',
      index: 24,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 42( )',
      englishTitle: 'psalm 42',
      arabicTitle: 'مزامير 42',
      index: 25,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 44( )',
      englishTitle: 'psalm 44',
      arabicTitle: 'مزامير 44',
      index: 26,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 45( )',
      englishTitle: 'psalm 45',
      arabicTitle: 'مزامير 45',
      index: 27,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 46( )',
      englishTitle: 'psalm 46',
      arabicTitle: 'مزامير 46',
      index: 28,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 53( )',
      englishTitle: 'psalm 53',
      arabicTitle: 'مزامير 53',
      index: 29,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 56( )',
      englishTitle: 'psalm 56',
      arabicTitle: 'مزامير 56',
      index: 30,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 60( )',
      englishTitle: 'psalm 60',
      arabicTitle: 'مزامير 60',
      index: 31,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 62( )',
      englishTitle: 'psalm 62',
      arabicTitle: 'مزامير 62',
      index: 32,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 66( )',
      englishTitle: 'psalm 66',
      arabicTitle: 'مزامير 66',
      index: 33,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 69( )',
      englishTitle: 'psalm 69',
      arabicTitle: 'مزامير 69',
      index: 34,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 83( )',
      englishTitle: 'psalm 83',
      arabicTitle: 'مزامير 83',
      index: 35,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 84( )',
      englishTitle: 'psalm 84',
      arabicTitle: 'مزامير 84',
      index: 36,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 85( )',
      englishTitle: 'psalm 85',
      arabicTitle: 'مزامير 85',
      index: 37,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 86( )',
      englishTitle: 'psalm 86',
      arabicTitle: 'مزامير 86',
      index: 38,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 90( )',
      englishTitle: 'psalm 90',
      arabicTitle: 'مزامير 90',
      index: 39,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 92( )',
      englishTitle: 'psalm 92',
      arabicTitle: 'مزامير 92',
      index: 40,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 95( )',
      englishTitle: 'psalm 95',
      arabicTitle: 'مزامير 95',
      index: 41,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 96( )',
      englishTitle: 'psalm 96',
      arabicTitle: 'مزامير 96',
      index: 42,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 97( )',
      englishTitle: 'psalm 97',
      arabicTitle: 'مزامير 97',
      index: 43,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 98( )',
      englishTitle: 'psalm 98',
      arabicTitle: 'مزامير 98',
      index: 44,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 99( )',
      englishTitle: 'psalm 99',
      arabicTitle: 'مزامير 99',
      index: 45,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 100( )',
      englishTitle: 'psalm 100',
      arabicTitle: 'مزامير 100',
      index: 46,
      copticTitle: '',
    ),
    Psalmmenu(
      japaneseTitle: '詩編(しへん) 109( )',
      englishTitle: 'psalm 109',
      arabicTitle: 'مزامير 109',
      index: 47,
      copticTitle: '',
    ),
  ];
}
