import 'package:flutter/material.dart';

class AgpyaMenu extends ChangeNotifier {
  final String JapaneseTitle;
  final String EnglishTitle;
  final String CopticTitle;
  final String ArabicTitle;
  final int index;

  AgpyaMenu({
    required this.CopticTitle,
    required this.JapaneseTitle,
    required this.EnglishTitle,
    required this.ArabicTitle,
    required this.index,
  });
  List<AgpyaMenu> get FirstHourMenu1 => firsthourmenu;
  List<AgpyaMenu> get ThirdHourMenu1 => Thirdhourmenu;
  List<AgpyaMenu> get SixthHourMenu1 => Sixthhourmenu;
  List<AgpyaMenu> get NinthHourMenu1 => Ninthhourmenu;
  List<AgpyaMenu> get Eleventhhourmenu1 => Eleventhhourmenu;
  List<AgpyaMenu> get Twelvethhourmenu1 => Twelvethhourmenu;

  static List<AgpyaMenu> firsthourmenu = [
    AgpyaMenu(
      JapaneseTitle: '朝礼(ちょうれい)',
      EnglishTitle: 'The First Hour',
      ArabicTitle: 'صلاة باكر ',
      index: 0,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 1,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '感謝(かんしゃ)の( )祈(いの)り( )',
      EnglishTitle: 'ThePrayerofThanksgiving ',
      ArabicTitle: 'صلاة الشكر',
      index: 2,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 50( )',
      EnglishTitle: 'Chapter 50',
      ArabicTitle: 'مزامير 50',
      index: 3,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'さあ、ひざまずきましょう。( )',
      EnglishTitle: 'ComeLetUsKneelDown',
      ArabicTitle: 'هلم نسجد',
      index: 4,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'エペソ人への( )手紙(てがみ)(4:1-5)( )',
      EnglishTitle: 'PaulineEpistle (Ephesians 4:1-5)',
      ArabicTitle: 'البولس من رسالة أفسس (4: 1-5)',
      index: 5,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '教会(きょうかい)の( )信仰(しんこう)',
      EnglishTitle: 'TheFaithofTheChurch',
      ArabicTitle: 'من إيمان الكنيسة',
      index: 6,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 1( )',
      EnglishTitle: 'psalm 1',
      ArabicTitle: 'مزامير 1',
      index: 7,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 2( )',
      EnglishTitle: 'psalm 2',
      ArabicTitle: 'مزامير 2',
      index: 8,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 3( )',
      EnglishTitle: 'psalm 3',
      ArabicTitle: 'مزامير 3',
      index: 9,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 4( )',
      EnglishTitle: 'psalm 4',
      ArabicTitle: 'مزامير 4',
      index: 10,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 5( )',
      EnglishTitle: 'psalm 5',
      ArabicTitle: 'مزامير 5',
      index: 11,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 6( )',
      EnglishTitle: 'psalm 6',
      ArabicTitle: 'مزامير 6',
      index: 12,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 8( )',
      EnglishTitle: 'psalm 8',
      ArabicTitle: 'مزامير 8',
      index: 13,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 11( )',
      EnglishTitle: 'psalm 11',
      ArabicTitle: 'مزامير 11',
      index: 14,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 12( )',
      EnglishTitle: 'psalm 12',
      ArabicTitle: 'مزامير 12',
      index: 15,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 14( )',
      EnglishTitle: 'psalm 14',
      ArabicTitle: 'مزامير 14',
      index: 16,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 15( )',
      EnglishTitle: 'psalm 15',
      ArabicTitle: 'مزامير 15',
      index: 17,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 18( )',
      EnglishTitle: 'psalm 18',
      ArabicTitle: 'مزامير 18',
      index: 18,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 24( )',
      EnglishTitle: 'psalm 24',
      ArabicTitle: 'مزامير 24',
      index: 19,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 26( )',
      EnglishTitle: 'psalm 26',
      ArabicTitle: 'مزامير 26',
      index: 20,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 62( )',
      EnglishTitle: 'psalm 62',
      ArabicTitle: 'مزامير 62',
      index: 21,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 66( )',
      EnglishTitle: 'psalm 66',
      ArabicTitle: 'مزامير 66',
      index: 22,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 69( )',
      EnglishTitle: 'psalm 69',
      ArabicTitle: 'مزامير 69',
      index: 23,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 112( )',
      EnglishTitle: 'psalm 112',
      ArabicTitle: 'مزامير 112',
      index: 24,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 142( )',
      EnglishTitle: 'psalm 142',
      ArabicTitle: 'مزامير 142',
      index: 25,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'ヨハネによる( )福音書(ふくいんしょ)(1:1-17)( )',
      EnglishTitle: 'Gospel (John 1:1-17)',
      ArabicTitle: '(إنجيل يوحنا 1: 1ـ17)',
      index: 26,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '連祷(れんとう)',
      EnglishTitle: 'Litanies',
      ArabicTitle: 'طلبة',
      index: 27,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'グロリア( )',
      EnglishTitle: 'The Gloria',
      ArabicTitle: 'تسبحه الملائكة',
      index: 28,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '聖三(せいさん)祝(しゅく)文(ぶん)の( )賛歌(さんか)アギオス( )',
      EnglishTitle: 'Trisagion',
      ArabicTitle: 'قدوس الله ',
      index: 29,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 30,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'あなたに( )喜(よろこ)びあれ。( )',
      EnglishTitle: 'Hail to You',
      ArabicTitle: 'السلام لك',
      index: 31,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '信条(しんじょう)の( )導入文(どうにゅうぶん)',
      EnglishTitle: 'Introduction to the Creed',
      ArabicTitle: 'بدء قانون الإيمان',
      index: 32,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'オーソドックス( )使徒(しと)信条(しんじょう)',
      EnglishTitle: 'The Orthdox Creed:',
      ArabicTitle: 'قانون الإيمان المقدس الأرثوذكسي:',
      index: 33,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '聖(せい)なる、( )聖(せい)なる、( )聖(せい)なる( )',
      EnglishTitle: 'Holy,Holy,Holy',
      ArabicTitle: 'قدوس، قدوس، قدوس',
      index: 34,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 35,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '最初(さいしょ)の( )赦(ゆる)し( )',
      EnglishTitle: 'First Absolution',
      ArabicTitle: 'وهذا التحليل',
      index: 36,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '第二(だいに)の( )赦(ゆる)し( )',
      EnglishTitle: 'Second Absolution',
      ArabicTitle: 'تحليل آخر',
      index: 37,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'すべての( )時(とき)の( )結(むす)び( )',
      EnglishTitle: 'Conclusion of Every Hour',
      ArabicTitle: 'طلبة تقال آخر كل ساعة',
      index: 38,
      CopticTitle: '',
    ),
  ];
  static List<AgpyaMenu> Thirdhourmenu = [
    AgpyaMenu(
      JapaneseTitle: '3 ( )時(じ)の( )祈(いの)り( )',
      EnglishTitle: 'The Third Hour',
      ArabicTitle: 'صلاة الساعه الثالثة ',
      index: 0,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 1,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '感謝(かんしゃ)の( )祈(いの)り( )',
      EnglishTitle: 'ThePrayerofThanksgiving ',
      ArabicTitle: 'صلاة الشكر',
      index: 2,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 50( )',
      EnglishTitle: 'Chapter 50',
      ArabicTitle: 'مزامير 50',
      index: 3,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '序文(じょぶん)',
      EnglishTitle: 'Introduction',
      ArabicTitle: 'مقدمة',
      index: 4,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 19( )',
      EnglishTitle: 'psalm 19',
      ArabicTitle: 'مزامير 19',
      index: 5,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 22( )',
      EnglishTitle: 'psalm 22',
      ArabicTitle: 'مزامير 22',
      index: 6,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 23( )',
      EnglishTitle: 'psalm 23',
      ArabicTitle: '2مزامير 3',
      index: 7,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 25( )',
      EnglishTitle: 'psalm 25',
      ArabicTitle: 'مزامير 25',
      index: 8,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 28( )',
      EnglishTitle: 'psalm 28',
      ArabicTitle: 'مزامير 28',
      index: 9,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 29( )',
      EnglishTitle: 'psalm 29',
      ArabicTitle: 'مزامير 29',
      index: 10,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 33( )',
      EnglishTitle: 'psalm 33',
      ArabicTitle: 'مزامير 33',
      index: 11,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 40( )',
      EnglishTitle: 'psalm 40',
      ArabicTitle: 'مزامير 40',
      index: 12,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 42( )',
      EnglishTitle: 'psalm 42',
      ArabicTitle: 'مزامير 42',
      index: 13,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 44( )',
      EnglishTitle: 'psalm 44',
      ArabicTitle: 'مزامير 44',
      index: 14,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 45( )',
      EnglishTitle: 'psalm 45',
      ArabicTitle: 'مزامير 45',
      index: 15,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 46( )',
      EnglishTitle: 'psalm 46',
      ArabicTitle: 'مزامير 46',
      index: 16,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'ヨハネによる( )福音書(ふくいんしょ)(14:26-15:4)( )',
      EnglishTitle: 'Gospel (John 14:26-15:4)',
      ArabicTitle: '(إنجيل يوحنا 14:26 - 15:4)',
      index: 17,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '連祷(れんとう)',
      EnglishTitle: 'Litanies',
      ArabicTitle: 'طلبة',
      index: 18,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '聖(せい)なる、( )聖(せい)なる、( )聖(せい)なる( )',
      EnglishTitle: 'Holy,Holy,Holy',
      ArabicTitle: 'قدوس، قدوس، قدوس',
      index: 19,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 20,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '赦(ゆる)し( )',
      EnglishTitle: ' Absolution',
      ArabicTitle: 'التحليل',
      index: 21,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'すべての( )時(とき)の( )結(むす)び( )',
      EnglishTitle: 'Conclision of Every Hour',
      ArabicTitle: 'طلبة تقال آخر كل ساعة',
      index: 22,
      CopticTitle: '',
    ),
  ];
  static List<AgpyaMenu> Sixthhourmenu = [
    AgpyaMenu(
      JapaneseTitle: '6 ( )時(じ)の( )祈(いの)り( )',
      EnglishTitle: 'The Sixth Hour',
      ArabicTitle: 'صلاة الساعه السادسة ',
      index: 0,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 1,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '感謝(かんしゃ)の( )祈(いの)り( )',
      EnglishTitle: 'ThePrayerofThanksgiving ',
      ArabicTitle: 'صلاة الشكر',
      index: 2,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 50( )',
      EnglishTitle: 'Chapter 50',
      ArabicTitle: 'مزامير 50',
      index: 3,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '序文(じょぶん)',
      EnglishTitle: 'Introduction',
      ArabicTitle: 'مقدمة',
      index: 4,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 53( )',
      EnglishTitle: 'psalm 53',
      ArabicTitle: 'مزامير 53',
      index: 5,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 56( )',
      EnglishTitle: 'psalm 56',
      ArabicTitle: 'مزامير 56',
      index: 6,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 60( )',
      EnglishTitle: 'psalm 60',
      ArabicTitle: 'مزامير 60',
      index: 7,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 62( )',
      EnglishTitle: 'psalm 62',
      ArabicTitle: 'مزامير 62',
      index: 8,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 66( )',
      EnglishTitle: 'psalm 66',
      ArabicTitle: 'مزامير 66',
      index: 9,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 69( )',
      EnglishTitle: 'psalm 69',
      ArabicTitle: 'مزامير 69',
      index: 10,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 83( )',
      EnglishTitle: 'psalm 83',
      ArabicTitle: 'مزامير 83',
      index: 11,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 84( )',
      EnglishTitle: 'psalm 84',
      ArabicTitle: 'مزامير 84',
      index: 12,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 85( )',
      EnglishTitle: 'psalm 85',
      ArabicTitle: 'مزامير 85',
      index: 13,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 86( )',
      EnglishTitle: 'psalm 86',
      ArabicTitle: 'مزامير 86',
      index: 14,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 90( )',
      EnglishTitle: 'psalm 90',
      ArabicTitle: 'مزامير 90',
      index: 15,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 92( )',
      EnglishTitle: 'psalm 92',
      ArabicTitle: 'مزامير 92',
      index: 16,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'マタイによる( )福音書(ふくいんしょ)(5:1-16)( )',
      EnglishTitle: 'Gospel (Matthew 5:1-16)',
      ArabicTitle: '(إنجيل متى 5:1-16)',
      index: 17,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '連祷(れんとう)',
      EnglishTitle: 'Litanies',
      ArabicTitle: 'طلبة',
      index: 18,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '聖(せい)なる、( )聖(せい)なる、( )聖(せい)なる( )',
      EnglishTitle: 'Holy,Holy,Holy',
      ArabicTitle: 'قدوس، قدوس، قدوس',
      index: 19,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 20,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '赦(ゆる)し( )',
      EnglishTitle: ' Absolution',
      ArabicTitle: 'التحليل',
      index: 21,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'すべての( )時(とき)の( )結(むす)び( )',
      EnglishTitle: 'Conclision of Every Hour',
      ArabicTitle: 'طلبة تقال آخر كل ساعة',
      index: 22,
      CopticTitle: '',
    ),
  ];
  static List<AgpyaMenu> Ninthhourmenu = [
    AgpyaMenu(
      JapaneseTitle: '9 ( )時(じ)の( )祈(いの)り( )',
      EnglishTitle: 'The Ninth Hour',
      ArabicTitle: 'صلاة الساعه التاسعة ',
      index: 0,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 1,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '感謝(かんしゃ)の( )祈(いの)り( )',
      EnglishTitle: 'ThePrayerofThanksgiving ',
      ArabicTitle: 'صلاة الشكر',
      index: 2,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 50( )',
      EnglishTitle: 'Chapter 50',
      ArabicTitle: 'مزامير 50',
      index: 3,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '序文(じょぶん)',
      EnglishTitle: 'Introduction',
      ArabicTitle: 'مقدمة',
      index: 4,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 95( )',
      EnglishTitle: 'psalm 95',
      ArabicTitle: 'مزامير 95',
      index: 5,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 96( )',
      EnglishTitle: 'psalm 96',
      ArabicTitle: 'مزامير 96',
      index: 6,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 97( )',
      EnglishTitle: 'psalm 97',
      ArabicTitle: 'مزامير 97',
      index: 7,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 98( )',
      EnglishTitle: 'psalm 98',
      ArabicTitle: 'مزامير 98',
      index: 8,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 99( )',
      EnglishTitle: 'psalm 99',
      ArabicTitle: 'مزامير 99',
      index: 9,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 100( )',
      EnglishTitle: 'psalm 100',
      ArabicTitle: 'مزامير 100',
      index: 10,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 109( )',
      EnglishTitle: 'psalm 109',
      ArabicTitle: 'مزامير 109',
      index: 11,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 110( )',
      EnglishTitle: 'psalm 110',
      ArabicTitle: 'مزامير 110',
      index: 12,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 111( )',
      EnglishTitle: 'psalm 111',
      ArabicTitle: 'مزامير 111',
      index: 13,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 112( )',
      EnglishTitle: 'psalm 112',
      ArabicTitle: 'مزامير 112',
      index: 14,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 114( )',
      EnglishTitle: 'psalm 114',
      ArabicTitle: 'مزامير 114',
      index: 15,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 115( )',
      EnglishTitle: 'psalm 115',
      ArabicTitle: 'مزامير 115',
      index: 16,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'ルカによる( )福音書(ふくいんしょ)(9:10-17)( )',
      EnglishTitle: 'Gospel (Luka 9:10-17)',
      ArabicTitle: '(إنجيل لوقا 10:9-17)',
      index: 17,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '連祷(れんとう)',
      EnglishTitle: 'Litanies',
      ArabicTitle: 'طلبة',
      index: 18,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '聖(せい)なる、( )聖(せい)なる、( )聖(せい)なる( )',
      EnglishTitle: 'Holy,Holy,Holy',
      ArabicTitle: 'قدوس، قدوس، قدوس',
      index: 19,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 20,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '赦(ゆる)し( )',
      EnglishTitle: ' Absolution',
      ArabicTitle: 'التحليل',
      index: 21,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'すべての( )時(とき)の( )結(むす)び( )',
      EnglishTitle: 'Conclision of Every Hour',
      ArabicTitle: 'طلبة تقال آخر كل ساعة',
      index: 22,
      CopticTitle: '',
    ),
  ];

  static List<AgpyaMenu> Eleventhhourmenu = [
    AgpyaMenu(
      JapaneseTitle: '11 ( )時(じ)の( )祈(いの)り( )',
      EnglishTitle: 'The Eleventh Hour',
      ArabicTitle: '(الغروب)صلاة الساعه الحادية عشر  ',
      index: 0,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 1,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '感謝(かんしゃ)の( )祈(いの)り( )',
      EnglishTitle: 'ThePrayerofThanksgiving ',
      ArabicTitle: 'صلاة الشكر',
      index: 2,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 50( )',
      EnglishTitle: 'Chapter 50',
      ArabicTitle: 'مزامير 50',
      index: 3,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '序文(じょぶん)',
      EnglishTitle: 'Introduction',
      ArabicTitle: 'مقدمة',
      index: 4,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 116( )',
      EnglishTitle: 'psalm 116',
      ArabicTitle: 'مزامير 116',
      index: 5,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 117( )',
      EnglishTitle: 'psalm 117',
      ArabicTitle: 'مزامير 117',
      index: 6,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 119( )',
      EnglishTitle: 'psalm 119',
      ArabicTitle: 'مزامير 119',
      index: 7,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 120( )',
      EnglishTitle: 'psalm 120',
      ArabicTitle: 'مزامير 120',
      index: 8,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 121( )',
      EnglishTitle: 'psalm 121',
      ArabicTitle: 'مزامير 121',
      index: 9,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 122( )',
      EnglishTitle: 'psalm 122',
      ArabicTitle: 'مزامير 122',
      index: 10,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 123( )',
      EnglishTitle: 'psalm 123',
      ArabicTitle: 'مزامير 123',
      index: 11,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 124( )',
      EnglishTitle: 'psalm 124',
      ArabicTitle: 'مزامير 124',
      index: 12,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 125( )',
      EnglishTitle: 'psalm 125',
      ArabicTitle: 'مزامير 125',
      index: 13,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 126( )',
      EnglishTitle: 'psalm 126',
      ArabicTitle: 'مزامير 126',
      index: 14,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 127( )',
      EnglishTitle: 'psalm 127',
      ArabicTitle: 'مزامير 127',
      index: 15,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 128( )',
      EnglishTitle: 'psalm 128',
      ArabicTitle: 'مزامير 128',
      index: 16,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'ルカによる( )福音書(ふくいんしょ)(4:38-41)',
      EnglishTitle: 'Gospel (Luka 4:38-41)',
      ArabicTitle: '(إنجيل لوقا 38:4-41)',
      index: 17,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '連祷(れんとう)',
      EnglishTitle: 'Litanies',
      ArabicTitle: 'طلبة',
      index: 18,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '聖(せい)なる、( )聖(せい)なる、( )聖(せい)なる( )',
      EnglishTitle: 'Holy,Holy,Holy',
      ArabicTitle: 'قدوس، قدوس، قدوس',
      index: 19,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 20,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '赦(ゆる)し( )',
      EnglishTitle: ' Absolution',
      ArabicTitle: 'التحليل',
      index: 21,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'すべての( )時(とき)の( )結(むす)び( )',
      EnglishTitle: 'Conclision of Every Hour',
      ArabicTitle: 'طلبة تقال آخر كل ساعة',
      index: 22,
      CopticTitle: '',
    ),
  ];
  static List<AgpyaMenu> Twelvethhourmenu = [
    AgpyaMenu(
      JapaneseTitle: '12 ( )時(じ)の( )祈(いの)り( )',
      EnglishTitle: 'The Twelveth Hour',
      ArabicTitle: '(النوم)صلاة الساعه الثانية عشر  ',
      index: 0,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 1,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '感謝(かんしゃ)の( )祈(いの)り( )',
      EnglishTitle: 'ThePrayerofThanksgiving ',
      ArabicTitle: 'صلاة الشكر',
      index: 2,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 50( )',
      EnglishTitle: 'Chapter 50',
      ArabicTitle: 'مزامير 50',
      index: 3,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '序文(じょぶん)',
      EnglishTitle: 'Introduction',
      ArabicTitle: 'مقدمة',
      index: 4,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 129( )',
      EnglishTitle: 'psalm 129',
      ArabicTitle: 'مزامير 129',
      index: 5,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 130( )',
      EnglishTitle: 'psalm 130',
      ArabicTitle: 'مزامير 130',
      index: 6,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 131( )',
      EnglishTitle: 'psalm 131',
      ArabicTitle: 'مزامير 131',
      index: 7,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 132( )',
      EnglishTitle: 'psalm 132',
      ArabicTitle: 'مزامير 132',
      index: 8,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 133( )',
      EnglishTitle: 'psalm 133',
      ArabicTitle: 'مزامير 133',
      index: 9,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 136( )',
      EnglishTitle: 'psalm 136',
      ArabicTitle: 'مزامير 136',
      index: 10,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 137( )',
      EnglishTitle: 'psalm 137',
      ArabicTitle: 'مزامير 137',
      index: 11,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 140( )',
      EnglishTitle: 'psalm 140',
      ArabicTitle: 'مزامير 140',
      index: 12,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 141( )',
      EnglishTitle: 'psalm 141',
      ArabicTitle: 'مزامير 141',
      index: 13,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 145( )',
      EnglishTitle: 'psalm 145',
      ArabicTitle: 'مزامير 145',
      index: 14,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 146( )',
      EnglishTitle: 'psalm 146',
      ArabicTitle: 'مزامير 146',
      index: 15,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '詩編(しへん) 147( )',
      EnglishTitle: 'psalm 147',
      ArabicTitle: 'مزامير 147',
      index: 16,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'ルカによる( )福音書(ふくいんしょ)(2:25-32)',
      EnglishTitle: 'Gospel (Luka 2:25-32)',
      ArabicTitle: '(إنجيل لوقا 25:2-32)',
      index: 17,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '連祷(れんとう)',
      EnglishTitle: 'Litanies',
      ArabicTitle: 'طلبة',
      index: 18,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '',
      EnglishTitle: 'Graciously Accord, O Lord',
      ArabicTitle: 'تفضل يارب',
      index: 19,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '聖三(せいさん)祝(しゅく)文(ぶん)の( )賛歌(さんか)アギオス( )',
      EnglishTitle: 'Trisagion',
      ArabicTitle: 'قدوس الله ',
      index: 20,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 21,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'あなたに( )喜(よろこ)びあれ。( )',
      EnglishTitle: 'Hail to You',
      ArabicTitle: 'السلام لك',
      index: 22,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '信条(しんじょう)の( )導入文(どうにゅうぶん)',
      EnglishTitle: 'Introduction to the Creed',
      ArabicTitle: 'بدء قانون الإيمان',
      index: 23,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'オーソドックス( )使徒(しと)信条(しんじょう)',
      EnglishTitle: 'The Orthdox Creed:',
      ArabicTitle: 'قانون الإيمان المقدس الأرثوذكسي:',
      index: 24,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '聖(せい)なる、( )聖(せい)なる、( )聖(せい)なる( )',
      EnglishTitle: 'Holy,Holy,Holy',
      ArabicTitle: 'قدوس، قدوس، قدوس',
      index: 25,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '天(てん)におられる( )',
      EnglishTitle: 'OurFather ',
      ArabicTitle: 'الصلاة الربانية',
      index: 26,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: '赦(ゆる)し( )',
      EnglishTitle: ' Absolution',
      ArabicTitle: 'التحليل',
      index: 27,
      CopticTitle: '',
    ),
    AgpyaMenu(
      JapaneseTitle: 'すべての( )時(とき)の( )結(むす)び( )',
      EnglishTitle: 'Conclision of Every Hour',
      ArabicTitle: 'طلبة تقال آخر كل ساعة',
      index: 28,
      CopticTitle: '',
    ),
  ];
}
