import 'package:flutter/material.dart';

class AgpyaMenu extends ChangeNotifier {
  final String japaneseTitle;
  final String englishTitle;
  final String copticTitle;
  final String arabicTitle;
  final int index;

  AgpyaMenu({
    required this.copticTitle,
    required this.japaneseTitle,
    required this.englishTitle,
    required this.arabicTitle,
    required this.index,
  });
  List<AgpyaMenu> get firstHourMenu1 => firsthourmenu;
  List<AgpyaMenu> get thirdHourMenu1 => thirdhourmenu;
  List<AgpyaMenu> get sixthHourMenu1 => sixthhourmenu;
  List<AgpyaMenu> get ninthHourMenu1 => ninthhourmenu;
  List<AgpyaMenu> get eleventhhourmenu1 => eleventhhourmenu;
  List<AgpyaMenu> get twelvethhourmenu1 => twelvethhourmenu;

  static List<AgpyaMenu> firsthourmenu = [
    AgpyaMenu(
      japaneseTitle: '朝礼(ちょうれい)',
      englishTitle: 'The First Hour',
      arabicTitle: 'صلاة باكر ',
      index: 0,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 1,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '感謝(かんしゃ)の( )祈(いの)り( )',
      englishTitle: 'ThePrayerofThanksgiving ',
      arabicTitle: 'صلاة الشكر',
      index: 2,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 50( )',
      englishTitle: 'Chapter 50',
      arabicTitle: 'مزامير 50',
      index: 3,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'さあ、ひざまずきましょう。( )',
      englishTitle: 'ComeLetUsKneelDown',
      arabicTitle: 'هلم نسجد',
      index: 4,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'エペソ人への( )手紙(てがみ)(4:1-5)( )',
      englishTitle: 'PaulineEpistle (Ephesians 4:1-5)',
      arabicTitle: 'البولس من رسالة أفسس (4: 1-5)',
      index: 5,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '教会(きょうかい)の( )信仰(しんこう)',
      englishTitle: 'TheFaithofTheChurch',
      arabicTitle: 'من إيمان الكنيسة',
      index: 6,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 1( )',
      englishTitle: 'psalm 1',
      arabicTitle: 'مزامير 1',
      index: 7,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 2( )',
      englishTitle: 'psalm 2',
      arabicTitle: 'مزامير 2',
      index: 8,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 3( )',
      englishTitle: 'psalm 3',
      arabicTitle: 'مزامير 3',
      index: 9,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 4( )',
      englishTitle: 'psalm 4',
      arabicTitle: 'مزامير 4',
      index: 10,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 5( )',
      englishTitle: 'psalm 5',
      arabicTitle: 'مزامير 5',
      index: 11,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 6( )',
      englishTitle: 'psalm 6',
      arabicTitle: 'مزامير 6',
      index: 12,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 8( )',
      englishTitle: 'psalm 8',
      arabicTitle: 'مزامير 8',
      index: 13,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 11( )',
      englishTitle: 'psalm 11',
      arabicTitle: 'مزامير 11',
      index: 14,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 12( )',
      englishTitle: 'psalm 12',
      arabicTitle: 'مزامير 12',
      index: 15,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 14( )',
      englishTitle: 'psalm 14',
      arabicTitle: 'مزامير 14',
      index: 16,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 15( )',
      englishTitle: 'psalm 15',
      arabicTitle: 'مزامير 15',
      index: 17,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 18( )',
      englishTitle: 'psalm 18',
      arabicTitle: 'مزامير 18',
      index: 18,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 24( )',
      englishTitle: 'psalm 24',
      arabicTitle: 'مزامير 24',
      index: 19,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 26( )',
      englishTitle: 'psalm 26',
      arabicTitle: 'مزامير 26',
      index: 20,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 62( )',
      englishTitle: 'psalm 62',
      arabicTitle: 'مزامير 62',
      index: 21,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 66( )',
      englishTitle: 'psalm 66',
      arabicTitle: 'مزامير 66',
      index: 22,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 69( )',
      englishTitle: 'psalm 69',
      arabicTitle: 'مزامير 69',
      index: 23,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 112( )',
      englishTitle: 'psalm 112',
      arabicTitle: 'مزامير 112',
      index: 24,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 142( )',
      englishTitle: 'psalm 142',
      arabicTitle: 'مزامير 142',
      index: 25,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'ヨハネによる( )福音書(ふくいんしょ)(1:1-17)( )',
      englishTitle: 'Gospel (John 1:1-17)',
      arabicTitle: '(إنجيل يوحنا 1: 1ـ17)',
      index: 26,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '連祷(れんとう)',
      englishTitle: 'Litanies',
      arabicTitle: 'طلبة',
      index: 27,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'グロリア( )',
      englishTitle: 'The Gloria',
      arabicTitle: 'تسبحه الملائكة',
      index: 28,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '聖三(せいさん)祝(しゅく)文(ぶん)の( )賛歌(さんか)アギオス( )',
      englishTitle: 'Trisagion',
      arabicTitle: 'قدوس الله ',
      index: 29,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 30,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'あなたに( )喜(よろこ)びあれ。( )',
      englishTitle: 'Hail to You',
      arabicTitle: 'السلام لك',
      index: 31,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '信条(しんじょう)の( )導入文(どうにゅうぶん)',
      englishTitle: 'Introduction to the Creed',
      arabicTitle: 'بدء قانون الإيمان',
      index: 32,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'オーソドックス( )使徒(しと)信条(しんじょう)',
      englishTitle: 'The Orthdox Creed:',
      arabicTitle: 'قانون الإيمان المقدس الأرثوذكسي:',
      index: 33,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '聖(せい)なる、( )聖(せい)なる、( )聖(せい)なる( )',
      englishTitle: 'Holy,Holy,Holy',
      arabicTitle: 'قدوس، قدوس، قدوس',
      index: 34,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 35,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '最初(さいしょ)の( )赦(ゆる)し( )',
      englishTitle: 'First Absolution',
      arabicTitle: 'وهذا التحليل',
      index: 36,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '第二(だいに)の( )赦(ゆる)し( )',
      englishTitle: 'Second Absolution',
      arabicTitle: 'تحليل آخر',
      index: 37,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'すべての( )時(とき)の( )結(むす)び( )',
      englishTitle: 'Conclusion of Every Hour',
      arabicTitle: 'طلبة تقال آخر كل ساعة',
      index: 38,
      copticTitle: '',
    ),
  ];
  static List<AgpyaMenu> thirdhourmenu = [
    AgpyaMenu(
      japaneseTitle: '3 ( )時(じ)の( )祈(いの)り( )',
      englishTitle: 'The Third Hour',
      arabicTitle: 'صلاة الساعه الثالثة ',
      index: 0,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 1,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '感謝(かんしゃ)の( )祈(いの)り( )',
      englishTitle: 'ThePrayerofThanksgiving ',
      arabicTitle: 'صلاة الشكر',
      index: 2,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 50( )',
      englishTitle: 'Chapter 50',
      arabicTitle: 'مزامير 50',
      index: 3,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '序文(じょぶん)',
      englishTitle: 'Introduction',
      arabicTitle: 'مقدمة',
      index: 4,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 19( )',
      englishTitle: 'psalm 19',
      arabicTitle: 'مزامير 19',
      index: 5,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 22( )',
      englishTitle: 'psalm 22',
      arabicTitle: 'مزامير 22',
      index: 6,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 23( )',
      englishTitle: 'psalm 23',
      arabicTitle: '2مزامير 3',
      index: 7,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 25( )',
      englishTitle: 'psalm 25',
      arabicTitle: 'مزامير 25',
      index: 8,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 28( )',
      englishTitle: 'psalm 28',
      arabicTitle: 'مزامير 28',
      index: 9,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 29( )',
      englishTitle: 'psalm 29',
      arabicTitle: 'مزامير 29',
      index: 10,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 33( )',
      englishTitle: 'psalm 33',
      arabicTitle: 'مزامير 33',
      index: 11,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 40( )',
      englishTitle: 'psalm 40',
      arabicTitle: 'مزامير 40',
      index: 12,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 42( )',
      englishTitle: 'psalm 42',
      arabicTitle: 'مزامير 42',
      index: 13,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 44( )',
      englishTitle: 'psalm 44',
      arabicTitle: 'مزامير 44',
      index: 14,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 45( )',
      englishTitle: 'psalm 45',
      arabicTitle: 'مزامير 45',
      index: 15,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 46( )',
      englishTitle: 'psalm 46',
      arabicTitle: 'مزامير 46',
      index: 16,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'ヨハネによる( )福音書(ふくいんしょ)(14:26-15:4)( )',
      englishTitle: 'Gospel (John 14:26-15:4)',
      arabicTitle: '(إنجيل يوحنا 14:26 - 15:4)',
      index: 17,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '連祷(れんとう)',
      englishTitle: 'Litanies',
      arabicTitle: 'طلبة',
      index: 18,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '聖(せい)なる、( )聖(せい)なる、( )聖(せい)なる( )',
      englishTitle: 'Holy,Holy,Holy',
      arabicTitle: 'قدوس، قدوس، قدوس',
      index: 19,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 20,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '赦(ゆる)し( )',
      englishTitle: ' Absolution',
      arabicTitle: 'التحليل',
      index: 21,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'すべての( )時(とき)の( )結(むす)び( )',
      englishTitle: 'Conclision of Every Hour',
      arabicTitle: 'طلبة تقال آخر كل ساعة',
      index: 22,
      copticTitle: '',
    ),
  ];
  static List<AgpyaMenu> sixthhourmenu = [
    AgpyaMenu(
      japaneseTitle: '6 ( )時(じ)の( )祈(いの)り( )',
      englishTitle: 'The Sixth Hour',
      arabicTitle: 'صلاة الساعه السادسة ',
      index: 0,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 1,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '感謝(かんしゃ)の( )祈(いの)り( )',
      englishTitle: 'ThePrayerofThanksgiving ',
      arabicTitle: 'صلاة الشكر',
      index: 2,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 50( )',
      englishTitle: 'Chapter 50',
      arabicTitle: 'مزامير 50',
      index: 3,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '序文(じょぶん)',
      englishTitle: 'Introduction',
      arabicTitle: 'مقدمة',
      index: 4,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 53( )',
      englishTitle: 'psalm 53',
      arabicTitle: 'مزامير 53',
      index: 5,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 56( )',
      englishTitle: 'psalm 56',
      arabicTitle: 'مزامير 56',
      index: 6,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 60( )',
      englishTitle: 'psalm 60',
      arabicTitle: 'مزامير 60',
      index: 7,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 62( )',
      englishTitle: 'psalm 62',
      arabicTitle: 'مزامير 62',
      index: 8,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 66( )',
      englishTitle: 'psalm 66',
      arabicTitle: 'مزامير 66',
      index: 9,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 69( )',
      englishTitle: 'psalm 69',
      arabicTitle: 'مزامير 69',
      index: 10,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 83( )',
      englishTitle: 'psalm 83',
      arabicTitle: 'مزامير 83',
      index: 11,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 84( )',
      englishTitle: 'psalm 84',
      arabicTitle: 'مزامير 84',
      index: 12,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 85( )',
      englishTitle: 'psalm 85',
      arabicTitle: 'مزامير 85',
      index: 13,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 86( )',
      englishTitle: 'psalm 86',
      arabicTitle: 'مزامير 86',
      index: 14,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 90( )',
      englishTitle: 'psalm 90',
      arabicTitle: 'مزامير 90',
      index: 15,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 92( )',
      englishTitle: 'psalm 92',
      arabicTitle: 'مزامير 92',
      index: 16,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'マタイによる( )福音書(ふくいんしょ)(5:1-16)( )',
      englishTitle: 'Gospel (Matthew 5:1-16)',
      arabicTitle: '(إنجيل متى 5:1-16)',
      index: 17,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '連祷(れんとう)',
      englishTitle: 'Litanies',
      arabicTitle: 'طلبة',
      index: 18,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '聖(せい)なる、( )聖(せい)なる、( )聖(せい)なる( )',
      englishTitle: 'Holy,Holy,Holy',
      arabicTitle: 'قدوس، قدوس، قدوس',
      index: 19,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 20,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '赦(ゆる)し( )',
      englishTitle: ' Absolution',
      arabicTitle: 'التحليل',
      index: 21,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'すべての( )時(とき)の( )結(むす)び( )',
      englishTitle: 'Conclision of Every Hour',
      arabicTitle: 'طلبة تقال آخر كل ساعة',
      index: 22,
      copticTitle: '',
    ),
  ];
  static List<AgpyaMenu> ninthhourmenu = [
    AgpyaMenu(
      japaneseTitle: '9 ( )時(じ)の( )祈(いの)り( )',
      englishTitle: 'The Ninth Hour',
      arabicTitle: 'صلاة الساعه التاسعة ',
      index: 0,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 1,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '感謝(かんしゃ)の( )祈(いの)り( )',
      englishTitle: 'ThePrayerofThanksgiving ',
      arabicTitle: 'صلاة الشكر',
      index: 2,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 50( )',
      englishTitle: 'Chapter 50',
      arabicTitle: 'مزامير 50',
      index: 3,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '序文(じょぶん)',
      englishTitle: 'Introduction',
      arabicTitle: 'مقدمة',
      index: 4,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 95( )',
      englishTitle: 'psalm 95',
      arabicTitle: 'مزامير 95',
      index: 5,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 96( )',
      englishTitle: 'psalm 96',
      arabicTitle: 'مزامير 96',
      index: 6,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 97( )',
      englishTitle: 'psalm 97',
      arabicTitle: 'مزامير 97',
      index: 7,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 98( )',
      englishTitle: 'psalm 98',
      arabicTitle: 'مزامير 98',
      index: 8,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 99( )',
      englishTitle: 'psalm 99',
      arabicTitle: 'مزامير 99',
      index: 9,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 100( )',
      englishTitle: 'psalm 100',
      arabicTitle: 'مزامير 100',
      index: 10,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 109( )',
      englishTitle: 'psalm 109',
      arabicTitle: 'مزامير 109',
      index: 11,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 110( )',
      englishTitle: 'psalm 110',
      arabicTitle: 'مزامير 110',
      index: 12,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 111( )',
      englishTitle: 'psalm 111',
      arabicTitle: 'مزامير 111',
      index: 13,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 112( )',
      englishTitle: 'psalm 112',
      arabicTitle: 'مزامير 112',
      index: 14,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 114( )',
      englishTitle: 'psalm 114',
      arabicTitle: 'مزامير 114',
      index: 15,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 115( )',
      englishTitle: 'psalm 115',
      arabicTitle: 'مزامير 115',
      index: 16,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'ルカによる( )福音書(ふくいんしょ)(9:10-17)( )',
      englishTitle: 'Gospel (Luka 9:10-17)',
      arabicTitle: '(إنجيل لوقا 10:9-17)',
      index: 17,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '連祷(れんとう)',
      englishTitle: 'Litanies',
      arabicTitle: 'طلبة',
      index: 18,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '聖(せい)なる、( )聖(せい)なる、( )聖(せい)なる( )',
      englishTitle: 'Holy,Holy,Holy',
      arabicTitle: 'قدوس، قدوس، قدوس',
      index: 19,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 20,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '赦(ゆる)し( )',
      englishTitle: ' Absolution',
      arabicTitle: 'التحليل',
      index: 21,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'すべての( )時(とき)の( )結(むす)び( )',
      englishTitle: 'Conclision of Every Hour',
      arabicTitle: 'طلبة تقال آخر كل ساعة',
      index: 22,
      copticTitle: '',
    ),
  ];

  static List<AgpyaMenu> eleventhhourmenu = [
    AgpyaMenu(
      japaneseTitle: '11 ( )時(じ)の( )祈(いの)り( )',
      englishTitle: 'The Eleventh Hour',
      arabicTitle: '(الغروب)صلاة الساعه الحادية عشر  ',
      index: 0,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 1,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '感謝(かんしゃ)の( )祈(いの)り( )',
      englishTitle: 'ThePrayerofThanksgiving ',
      arabicTitle: 'صلاة الشكر',
      index: 2,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 50( )',
      englishTitle: 'Chapter 50',
      arabicTitle: 'مزامير 50',
      index: 3,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '序文(じょぶん)',
      englishTitle: 'Introduction',
      arabicTitle: 'مقدمة',
      index: 4,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 116( )',
      englishTitle: 'psalm 116',
      arabicTitle: 'مزامير 116',
      index: 5,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 117( )',
      englishTitle: 'psalm 117',
      arabicTitle: 'مزامير 117',
      index: 6,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 119( )',
      englishTitle: 'psalm 119',
      arabicTitle: 'مزامير 119',
      index: 7,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 120( )',
      englishTitle: 'psalm 120',
      arabicTitle: 'مزامير 120',
      index: 8,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 121( )',
      englishTitle: 'psalm 121',
      arabicTitle: 'مزامير 121',
      index: 9,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 122( )',
      englishTitle: 'psalm 122',
      arabicTitle: 'مزامير 122',
      index: 10,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 123( )',
      englishTitle: 'psalm 123',
      arabicTitle: 'مزامير 123',
      index: 11,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 124( )',
      englishTitle: 'psalm 124',
      arabicTitle: 'مزامير 124',
      index: 12,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 125( )',
      englishTitle: 'psalm 125',
      arabicTitle: 'مزامير 125',
      index: 13,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 126( )',
      englishTitle: 'psalm 126',
      arabicTitle: 'مزامير 126',
      index: 14,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 127( )',
      englishTitle: 'psalm 127',
      arabicTitle: 'مزامير 127',
      index: 15,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 128( )',
      englishTitle: 'psalm 128',
      arabicTitle: 'مزامير 128',
      index: 16,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'ルカによる( )福音書(ふくいんしょ)(4:38-41)',
      englishTitle: 'Gospel (Luka 4:38-41)',
      arabicTitle: '(إنجيل لوقا 38:4-41)',
      index: 17,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '連祷(れんとう)',
      englishTitle: 'Litanies',
      arabicTitle: 'طلبة',
      index: 18,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '聖(せい)なる、( )聖(せい)なる、( )聖(せい)なる( )',
      englishTitle: 'Holy,Holy,Holy',
      arabicTitle: 'قدوس، قدوس، قدوس',
      index: 19,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 20,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '赦(ゆる)し( )',
      englishTitle: ' Absolution',
      arabicTitle: 'التحليل',
      index: 21,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'すべての( )時(とき)の( )結(むす)び( )',
      englishTitle: 'Conclision of Every Hour',
      arabicTitle: 'طلبة تقال آخر كل ساعة',
      index: 22,
      copticTitle: '',
    ),
  ];
  static List<AgpyaMenu> twelvethhourmenu = [
    AgpyaMenu(
      japaneseTitle: '12 ( )時(じ)の( )祈(いの)り( )',
      englishTitle: 'The Twelveth Hour',
      arabicTitle: '(النوم)صلاة الساعه الثانية عشر  ',
      index: 0,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 1,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '感謝(かんしゃ)の( )祈(いの)り( )',
      englishTitle: 'ThePrayerofThanksgiving ',
      arabicTitle: 'صلاة الشكر',
      index: 2,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 50( )',
      englishTitle: 'Chapter 50',
      arabicTitle: 'مزامير 50',
      index: 3,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '序文(じょぶん)',
      englishTitle: 'Introduction',
      arabicTitle: 'مقدمة',
      index: 4,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 129( )',
      englishTitle: 'psalm 129',
      arabicTitle: 'مزامير 129',
      index: 5,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 130( )',
      englishTitle: 'psalm 130',
      arabicTitle: 'مزامير 130',
      index: 6,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 131( )',
      englishTitle: 'psalm 131',
      arabicTitle: 'مزامير 131',
      index: 7,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 132( )',
      englishTitle: 'psalm 132',
      arabicTitle: 'مزامير 132',
      index: 8,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 133( )',
      englishTitle: 'psalm 133',
      arabicTitle: 'مزامير 133',
      index: 9,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 136( )',
      englishTitle: 'psalm 136',
      arabicTitle: 'مزامير 136',
      index: 10,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 137( )',
      englishTitle: 'psalm 137',
      arabicTitle: 'مزامير 137',
      index: 11,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 140( )',
      englishTitle: 'psalm 140',
      arabicTitle: 'مزامير 140',
      index: 12,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 141( )',
      englishTitle: 'psalm 141',
      arabicTitle: 'مزامير 141',
      index: 13,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 145( )',
      englishTitle: 'psalm 145',
      arabicTitle: 'مزامير 145',
      index: 14,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 146( )',
      englishTitle: 'psalm 146',
      arabicTitle: 'مزامير 146',
      index: 15,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '詩編(しへん) 147( )',
      englishTitle: 'psalm 147',
      arabicTitle: 'مزامير 147',
      index: 16,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'ルカによる( )福音書(ふくいんしょ)(2:25-32)',
      englishTitle: 'Gospel (Luka 2:25-32)',
      arabicTitle: '(إنجيل لوقا 25:2-32)',
      index: 17,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '連祷(れんとう)',
      englishTitle: 'Litanies',
      arabicTitle: 'طلبة',
      index: 18,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '',
      englishTitle: 'Graciously Accord, O Lord',
      arabicTitle: 'تفضل يارب',
      index: 19,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '聖三(せいさん)祝(しゅく)文(ぶん)の( )賛歌(さんか)アギオス( )',
      englishTitle: 'Trisagion',
      arabicTitle: 'قدوس الله ',
      index: 20,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 21,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'あなたに( )喜(よろこ)びあれ。( )',
      englishTitle: 'Hail to You',
      arabicTitle: 'السلام لك',
      index: 22,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '信条(しんじょう)の( )導入文(どうにゅうぶん)',
      englishTitle: 'Introduction to the Creed',
      arabicTitle: 'بدء قانون الإيمان',
      index: 23,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'オーソドックス( )使徒(しと)信条(しんじょう)',
      englishTitle: 'The Orthdox Creed:',
      arabicTitle: 'قانون الإيمان المقدس الأرثوذكسي:',
      index: 24,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '聖(せい)なる、( )聖(せい)なる、( )聖(せい)なる( )',
      englishTitle: 'Holy,Holy,Holy',
      arabicTitle: 'قدوس، قدوس، قدوس',
      index: 25,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '天(てん)におられる( )',
      englishTitle: 'OurFather ',
      arabicTitle: 'الصلاة الربانية',
      index: 26,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: '赦(ゆる)し( )',
      englishTitle: ' Absolution',
      arabicTitle: 'التحليل',
      index: 27,
      copticTitle: '',
    ),
    AgpyaMenu(
      japaneseTitle: 'すべての( )時(とき)の( )結(むす)び( )',
      englishTitle: 'Conclision of Every Hour',
      arabicTitle: 'طلبة تقال آخر كل ساعة',
      index: 28,
      copticTitle: '',
    ),
  ];
}
